# Generated by Django 4.1.7 on 2023-10-02 18:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.AddField(
            model_name='companytranslation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companytranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companytranslation',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, default='NEW', null=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, default='NEW', null=True),
        ),
    ]
