# Generated by Django 5.0.7 on 2024-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="indexcategory",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="brand",
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Erkak (Male)"),
                    ("F", "Ayol (Female)"),
                    ("U", "Unisex"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
