# Generated by Django 4.2.11 on 2024-03-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recctegory_images', verbose_name='Rasm'),
        ),
    ]
