# Generated by Django 4.1.7 on 2023-10-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_company_location_companytranslation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytranslation',
            name='short_description',
            field=models.CharField(blank=True, default='NEW', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=models.CharField(blank=True, default='NEW', max_length=300, null=True),
        ),
    ]
