# Generated by Django 4.2.11 on 2024-03-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_orderitem_delete_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nomi', max_length=123)),
                ('star', models.IntegerField(default=0, verbose_name='star')),
                ('review_comment', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='review_created_date')),
                ('email', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productreview', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Rating',
                'verbose_name_plural': 'Product Ratings',
            },
        ),
    ]
