# Generated by Django 5.0.7 on 2024-09-05 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
